### ISSUE TITLE
UTF-8....

### ISSUE THREAD

**Issue by Xiao-yux** [KarisAya/nonebot-plugin-mcqq-guild#1]
![image](https://user-images.githubusercontent.com/79674967/193289775-5069acc6-fd37-44b6-87f2-0451a2509416.png)
这个怎么解决

**Comment by Xiao-yux** [comment]
![image](https://user-images.githubusercontent.com/79674967/193290863-3043ecfe-adb7-4255-91c5-a726d46bc2ec.png)
qq发不出消息

**Comment by KarisAya** [comment]
> ![image](https://user-images.githubusercontent.com/79674967/193290863-3043ecfe-adb7-4255-91c5-a726d46bc2ec.png) qq发不出消息

大概是因为你的mc服务器log文件不是utf8编码的，你看一下是什么格式

**Comment by Xiao-yux** [comment]
GB2312

**Comment by Xiao-yux** [comment]
我去把utf8改成GB2312后，没报错，但消息互通不了了，所以这个怎么办

**Comment by KarisAya** [comment]
> 我去把utf8改成GB2312后，没报错，但消息互通不了了，所以这个怎么办

问题解决了？

**Comment by Xiao-yux** [comment]
用别人插件了
